# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cosmo-datastore
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 10Gi  # You can adjust this based on your storage requirements
#   accessModes:
#     - ReadWriteOnce


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmo-datastore
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi